[theme]
name = 'Breeze'
comment = 'Breeze by the KDE VDG'
website = 'https://github.com/akiirui/breeze-for-windows'

[config]
bitmaps_dir = 'breeze/cursors/Breeze/build/x2/' # This config will assigned with `ctgen -d <path>`
out_dir = 'themes'
platforms = 'windows'

[cursors]

[cursors.fallback_settings]
win_sizes = [64]
x_hotspot = 32
y_hotspot = 32
win_delay = 1

[cursors.default]
png = 'default.png'
x_hotspot = 8
y_hotspot = 8
win_name = 'Pointer'

[cursors.help]
png = 'help.png'
x_hotspot = 8
y_hotspot = 8
win_name = 'Help'

[cursors.progress]
png = 'progress-*.png'
x_hotspot = 8
y_hotspot = 8
win_name = 'Work'

[cursors.wait]
png = 'wait-*.png'
win_name = 'Busy'

[cursors.cross]
png = 'crosshair.png'
win_name = 'Cross'

[cursors.text]
png = 'text.png'
win_name = 'Text'

[cursors.pencil]
png = 'pencil.png'
x_hotspot = 8
y_hotspot = 58
win_name = 'Handwriting'

[cursors.dnd_no_drop]
png = 'not-allowed.png'
win_name = 'Unavailable'

[cursors.size_ver]
png = 'size_ver.png'
win_name = 'Vert'

[cursors.size_hor]
png = 'size_hor.png'
win_name = 'Horz'

[cursors.size_fdiag]
png = 'size_fdiag.png'
win_name = 'Dgn1'

[cursors.size_bdiag]
png = 'size_bdiag.png'
win_name = 'Dgn2'

[cursors.move]
png = 'all-scroll.png'
win_name = 'Move'

[cursors.center_ptr]
png = 'center_ptr.png'
x_hotspot = 40
y_hotspot = 8
win_name = 'Alternate'

[cursors.pointer]
png = 'pointer.png'
x_hotspot = 32
y_hotspot = 8
win_name = 'Link'
