name: build
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          sudo apt-get install -y inkscape x11-apps qt6-base-dev
          pip install clickgen pyside6 attrs
        continue-on-error: false

      - name: Build Breeze Source
        working-directory: breeze/cursors/Breeze
        run: |
          bash ../src/build.sh

      - name: Build Breeze Light Source
        working-directory: breeze/cursors/Breeze_Light
        run: |
          bash ../src/build.sh

      - name: Build Breeze
        run: |
          ctgen build.toml -n 'Breeze' -d 'breeze/cursors/Breeze/build/x200/'
          ctgen build.toml -n 'Breeze-Light' -d 'breeze/cursors/Breeze_Light/build/x200/'

      - name: Package
        run: |
          zip -jr Breeze.zip themes/Breeze-Windows/
          zip -jr Breeze-Light.zip themes/Breeze-Light-Windows/
          sha512sum Breeze.zip Breeze-Light.zip > sha512sum

      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Breeze.zip,Breeze-Light.zip,sha512sum"
